//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Агент
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Агент()
        {
            this.Заявка = new HashSet<Заявка>();
            this.История = new HashSet<История>();
        }
    
        public int ID_Агента { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Номер_телефона { get; set; }
        public string email { get; set; }
        public byte[] Логотип { get; set; }
        public string Приоритет { get; set; }
        public string Скидка_агента { get; set; }
        public string Наименование_компании { get; set; }
        public string Тип_агента { get; set; }
        public string Юридический_адрес { get; set; }
        public Nullable<int> ИНН { get; set; }
        public string КПП { get; set; }
        public Nullable<int> ID_Предложения { get; set; }
        public string ФИО_иректора { get; set; }
        public Nullable<int> ID_Каталога { get; set; }
    
        public virtual Каталог_готовой_продукции Каталог_готовой_продукции { get; set; }
        public virtual Предложение_для_агента Предложение_для_агента { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заявка> Заявка { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<История> История { get; set; }
    }
}
