//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ_материалов
    {
        public int ID_Заказа_материалов { get; set; }
        public Nullable<int> ID_Материалы { get; set; }
        public string Тип_материала { get; set; }
        public string Заказанное_кол_во_ед_материала { get; set; }
        public Nullable<int> ID_Мастера { get; set; }
    
        public virtual Мастер_производства Мастер_производства { get; set; }
        public virtual Материалы Материалы { get; set; }
    }
}
