//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявка
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заявка()
        {
            this.Доставка = new HashSet<Доставка>();
        }
    
        public int ID_Заявки { get; set; }
        public Nullable<int> ID_Агента { get; set; }
        public Nullable<int> ID_Менеджера { get; set; }
        public string Дата_поступления_заявки { get; set; }
        public string Название { get; set; }
        public string Количество_товара { get; set; }
        public string Предоплата { get; set; }
        public string Статус_заявки { get; set; }
        public string Вариант_выдачи { get; set; }
    
        public virtual Агент Агент { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Доставка> Доставка { get; set; }
        public virtual Менеджер Менеджер { get; set; }
    }
}
