//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Материалы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Материалы()
        {
            this.Заказ_материалов = new HashSet<Заказ_материалов>();
        }
    
        public int ID_Материалы { get; set; }
        public string Наименование_материала { get; set; }
        public string Тип_материала { get; set; }
        public byte[] Изображение { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public Nullable<int> Количество_на_складе { get; set; }
        public Nullable<int> Минимальное_количество { get; set; }
        public Nullable<int> Количество_в_упаковке { get; set; }
        public string Единица_измерения { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказ_материалов> Заказ_материалов { get; set; }
    }
}
