//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сотрудники()
        {
            this.Статистика_по_сотруднику = new HashSet<Статистика_по_сотруднику>();
            this.Турникет = new HashSet<Турникет>();
        }
    
        public int ID_Сотрудника { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public string Серия_и_номер_паспорта { get; set; }
        public string Кем_выдан { get; set; }
        public string Место_прописки { get; set; }
        public string Фактическое_место_жительство { get; set; }
        public string Реквизиты { get; set; }
        public string Семейное_положение { get; set; }
        public string Здоровье { get; set; }
        public string Специализация { get; set; }
        public Nullable<int> ID_Цеха { get; set; }
        public Nullable<int> ID_Смены { get; set; }
        public Nullable<int> Уровень_доступа { get; set; }
    
        public virtual Смена Смена { get; set; }
        public virtual Цех Цех { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Статистика_по_сотруднику> Статистика_по_сотруднику { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Турникет> Турникет { get; set; }
    }
}
