//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Статистика_по_сотруднику
    {
        public int ID_Статистики { get; set; }
        public Nullable<int> ID_Сотрудника { get; set; }
        public Nullable<int> ID_Турникета { get; set; }
        public Nullable<System.DateTime> Время_входа { get; set; }
        public Nullable<System.DateTime> Время_выхода { get; set; }
    
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual Турникет Турникет { get; set; }
    }
}
